/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        surface: "#f4fcf0",
        "surface-dim": "#d5dcd1",
        "surface-bright": "#f4fcf0",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#eff6ea",
        "surface-container": "#e9f0e5",
        "surface-container-high": "#e3eadf",
        "surface-container-highest": "#dde5d9",
        "on-surface": "#171d16",
        "on-surface-variant": "#3e4a3d",
        "inverse-surface": "#2b322b",
        "inverse-on-surface": "#ecf3e7",
        outline: "#6e7b6c",
        "outline-variant": "#bdcaba",
        "surface-tint": "#006e2d",
        primary: "#006b2c",
        "on-primary": "#ffffff",
        "primary-container": "#00873a",
        "on-primary-container": "#f7fff2",
        "inverse-primary": "#62df7d",
        secondary: "#9d4300",
        "on-secondary": "#ffffff",
        "secondary-container": "#fd761a",
        "on-secondary-container": "#5c2400",
        tertiary: "#a72d51",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#c74668",
        "on-tertiary-container": "#fffbff",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        background: "#f4fcf0",
        "on-background": "#171d16",
        "surface-variant": "#dde5d9",
      },
      fontFamily: {
        sans: ["WorkSans_400Regular"],
        medium: ["WorkSans_500Medium"],
        semibold: ["WorkSans_600SemiBold"],
        bold: ["WorkSans_700Bold"],
      },
      borderRadius: {
        DEFAULT: "4px",
        md: "12px",
        lg: "16px",
        xl: "24px",
      },
    },
  },
  plugins: [],
};
